import { PujaItemConfig } from "./types";

export const ITEM_IMAGES: Record<string, any> = {
  sankh: require('../../assets/images/sankh.png'),
  mala: require('../../assets/images/mala.jpg'),
  flower: require('../../assets/images/rose.png'),
  flower_rose: require('../../assets/images/rose.png'),
  flower_marigold: require('../../assets/images/marigold.png'),
  flower_lotus: require('../../assets/images/lotus.png'),
  flower_jasmine: require('../../assets/images/jasmine.png'),
  flower_mogra: require('../../assets/images/mogra.png'),
  diya: require('../../assets/images/diya.png'),
  diya_oil: require('../../assets/images/oil_diya.png'),
  diya_ghee: require('../../assets/images/ghee_diya.png'),
  diya_candle: require('../../assets/images/candle.png'),
  diya_diya: require('../../assets/images/diya.png'),
  camara: require('../../assets/images/dhoop.png'),
  camara_dhoop: require('../../assets/images/dhoop.png'),
  camara_agarbatti: require('../../assets/images/agarbati.png'),
  camara_incense: require('../../assets/images/incense.png'),
  camara_chandan: require('../../assets/images/chandan.png'),
  kalash: require('../../assets/images/copper_kalash.png'),
  kalash_copper: require('../../assets/images/copper_kalash.png'),
  kalash_gold: require('../../assets/images/gold_kalash.png'),
  kalash_silver: require('../../assets/images/silver_kalash.png'),
  kalash_earthen: require('../../assets/images/earthen_kalash.png'),
  coconut: require('../../assets/images/coconut.png'),
  coconut_hard: require('../../assets/images/coconut.png'),
  coconut_tender: require('../../assets/images/tender_coconut.png'),
  coconut_decorated: require('../../assets/images/decorated_cocont.png'),
  coconut_copra: require('../../assets/images/copra_coconut.png'),
  // Laddu/Mithai options - using coconut as placeholder
  laddu: require('../../assets/images/laddu.png'),
  laddu_motichoor: require('../../assets/images/laddu_motichoor.png'),
  laddu_boondi: require('../../assets/images/laddu_boondi.png'),
  laddu_ghevar: require('../../assets/images/laddu_besan.png'),
  laddu_besan: require('../../assets/images/laddu_besan.png'),
};


// Define puja items with Hindi names (excluding mala, sankh, aarti)
 export const POOJA_ITEMS: PujaItemConfig[] = [
  {
    id: 'flower',
    name: 'Flower',
    nameHindi: 'फूल',
    iconName: 'flower',
    color: '#E91E63',
    soundFile: 'bell',
  },
  {
    id: 'diya',
    name: 'Diya',
    nameHindi: 'दीया',
    iconName: 'fire',
    color: '#FF9800',
    soundFile: 'bell',
  },
  {
    id: 'camara',
    name: 'Dhoop',
    nameHindi: 'धूप',
    iconName: 'cloud',
    color: '#8D6E63',
    soundFile: 'bell',
  },
  {
    id: 'kalash',
    name: 'Kalash',
    nameHindi: 'कलश',
    iconName: 'cup',
    color: '#4CAF50',
    soundFile: 'bell',
  },
  {
    id: 'coconut',
    name: 'Coconut',
    nameHindi: 'नारियल',
    iconName: 'fruit',
    color: '#795548',
    soundFile: 'bell',
  },
  {
    id: 'laddu',
    name: 'Laddu',
    nameHindi: 'लड्डू',
    iconName: 'cookie',
    color: '#FF9800',
    soundFile: 'bell',
  },
];