import {StyleSheet} from 'react-native';

export const dailyPujaScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'red',
    // justifyContent:'center',
    // alignItems:'center',
  },
  toggleButton: {
    position: 'absolute',
    bottom: 50,
    right: 15,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 152, 0, 0.8)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFD700',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  selectGodContainer: {
    position: 'absolute',
    bottom: 0,
  },
  startButtonContainer: {
    position: 'absolute',
    bottom: 30,
    alignSelf: 'center',
    alignItems: 'center',
  },
  startButtonGlow: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: '#FFD700',
  },
  startButton: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#FF9800',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: '#FFD700',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  startButtonActive: {
    backgroundColor: '#4CAF50',
    borderColor: '#81C784',
  },
  startButtonText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
  },
  startButtonSubText: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: '500',
    marginTop: 2,
  },
  stopAartiButton: {
    position: 'absolute',
    bottom: 50,
    alignSelf: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(244, 67, 54, 0.9)',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: '#FFF',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  stopAartiText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
  },
  flowerRainButton: {
    position: 'absolute',
    bottom: 160,
    alignSelf: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(233, 30, 99, 0.9)',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: '#FF4081',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  flowerRainButtonText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
  },
  flowerRainButtonTextHindi: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: '500',
    marginTop: 2,
  },
  completePujaButton: {
    position: 'absolute',
    bottom: 20,
    alignSelf: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(76, 175, 80, 0.9)',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: '#81C784',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  completePujaButtonText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
  },
  completePujaButtonTextHindi: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: '500',
    marginTop: 2,
  },
  resetButtonContainer: {
    position: 'absolute',
    bottom: 30,
    alignSelf: 'center',
    alignItems: 'center',
  },
  resetButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(33, 150, 243, 0.9)',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: '#64B5F6',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  resetButtonText: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '700',
    marginTop: 8,
  },
  resetButtonTextHindi: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '500',
    marginTop: 4,
  },
});

export default dailyPujaScreenStyles;
